### ISSUE TITLE
Wont work with webpack production mode

### ISSUE THREAD

**Issue by kvvinokurov** [IRCraziestTaxi/ts-simple-nameof#10] opened 2019-11-05 14:59 UTC
In console error: nameof function is undefined

**Comment by IRCraziestTaxi** [comment] 2019-11-25 16:36
Sorry for the delay in response to this issue.

There isn't a lot of information provided here. I have used this lib in production webpack (in an Angular app) in the past with no problems. Could you provide more steps to reproduce or even a small repro?

Thanks!

**Comment by weagle08** [comment] 2019-12-03 19:34
I have this problem as well when tsconfig target is set to es5, have to set target to es6 or higher for it to work even with correct polyfills. This should not be a problem unless you have to support IE11 or older.

**Comment by egorpavlikhin** [comment] 2020-04-02 04:42
Unfortunately in Angular the return looks like this
`AClass extends _CommsPlan__WEBPACK_IMPORTED_MODULE_0__["BClass"]`

**Comment by IRCraziestTaxi** [comment] 2020-05-19 02:25
Terribly sorry for the extra long delay in activity on this.

Fixed in `1.3.0`! :)

**Closed by IRCraziestTaxi** 2020-05-19 02:25 UTC
